version: '3'
services:
  php: 
    build: 
      context: ./
      dockerfile: docker/php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    restart: unless-stopped
    # ports:
    #   - "9000:9000"
    volumes:
      - ./playphp:/var/www/html:delegated
    depends_on:
      - database
      - webserver
    networks: 
      - laravel    

  database:
    image: mysql:8.0
    container_name: database
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=testbench
      # - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_ROOT_PASSWORD=123    
      # - MYSQL_PASSWORD=
    # ports:
    #   - 3306:80
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpadmin
    restart: always
    ports:
    # 8080 is the host port and 80 is the docker port
       - 8080:80
    environment:
      - PMA_ARBITRARY:1
      - PMA_HOST:mysql
      - MYSQL_USERNAME:root
      - MYSQL_ROOT_PASSWORD:123
    depends_on:
      - database
      - webserver
    networks:
    # define your network where all containers are connected to each other
      - laravel

  webserver:
    build: 
      dockerfile: ./docker/nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./playphp:/var/www/html
    networks:
      - laravel

networks:
  laravel:
    driver: bridge